In [1]:
data_list=[1,2,3]

In [2]:
data_list

[1, 2, 3]

In [3]:
import numpy as np

In [4]:
arr = np.array(data_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
data_list2= [[10,20,30],[40,50,60],[70,80,90]]

In [7]:
arr2 = np.array(data_list2)

In [8]:
arr2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [9]:
arr3=np.array([1,2,3,4,5,6])

In [10]:
arr3

array([1, 2, 3, 4, 5, 6])

In [11]:
arr3[1]

2

In [12]:
arr3[5]

6

In [13]:
arr2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [14]:
arr2[0,1]

20

In [15]:
arr2[2,2]

90

In [16]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [17]:
np.arange(0,100,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [18]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [22]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [23]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [25]:
np.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [26]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [84]:
np.random.randint(0,10)

2

In [85]:
np.random.randint(10)

0

In [53]:
np.random.randint(0,10,5)

array([6, 8, 6, 0, 5])

In [55]:
np.random.rand(5)

array([0.25363959, 0.14745324, 0.0970708 , 0.13606556, 0.58728009])

In [59]:
np.random.randn(5)

array([ 0.88281778,  0.52390295, -2.49930052,  0.35241797, -1.06548573])

In [60]:
arr = np.arange(25)

In [61]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [62]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [66]:
newArray = np.random.randint(0,100,5)

In [67]:
newArray

array([29,  6, 99, 91, 96])

In [68]:
newArray.max()

99

In [69]:
newArray.min()

6

In [70]:
newArray.sum()

321

In [71]:
newArray.mean()

64.2

In [72]:
newArray.argmax()

2

In [73]:
newArray.argmin()

1

In [74]:
detArray = np.random.randint(1,100,25)

In [75]:
detArray

array([48, 55,  6,  9, 97, 53, 74,  3, 78, 77, 48, 60, 40, 48, 58, 69, 41,
       91, 28, 58, 96, 47, 65, 32, 50])

In [76]:
detArray = detArray.reshape(5,5)

In [77]:
detArray

array([[48, 55,  6,  9, 97],
       [53, 74,  3, 78, 77],
       [48, 60, 40, 48, 58],
       [69, 41, 91, 28, 58],
       [96, 47, 65, 32, 50]])

In [78]:
np.linalg.det(detArray)

-255218710.0000003

In [80]:
detArray2 = np.array([[1,2],[3,4]])

In [81]:
detArray2

array([[1, 2],
       [3, 4]])

In [82]:
np.linalg.det(detArray2)

-2.0000000000000004

In [83]:
round(np.linalg.det(detArray2))

-2.0