In [1]:
import numpy as np

In [2]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.arange(2,100,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [9]:
np.ones(5)*10

array([10., 10., 10., 10., 10.])

In [10]:
np.arange(1,17).reshape(4,4)


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [11]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [48]:
np.random.rand()*5

2.799515200131923

In [49]:
np.random.randn(25).reshape(5,5)

array([[-0.46050958, -0.89209068,  0.23825781,  0.3543036 , -0.4925    ],
       [-1.11094502, -0.45056791,  0.67393143,  0.93738358,  0.37511444],
       [-1.23355591, -0.35782786,  0.77334556, -1.09521004,  0.53642611],
       [-0.0870616 ,  0.29014895, -1.46088239,  0.18098349, -0.41583522],
       [ 0.13599764,  0.77053238, -0.8160971 ,  1.13795858, -1.72653412]])

In [54]:
np.linspace(1,5,20) 

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [64]:
arr = np.arange(1,101).reshape(10,10)

In [65]:
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [69]:
arr[4:]

array([[ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [74]:
arr[6:,4:]

array([[ 65,  66,  67,  68,  69,  70],
       [ 75,  76,  77,  78,  79,  80],
       [ 85,  86,  87,  88,  89,  90],
       [ 95,  96,  97,  98,  99, 100]])

In [76]:
arr[:3,2:4]

array([[ 3,  4],
       [13, 14],
       [23, 24]])

In [85]:
arr[:3,1] 

array([ 2, 12, 22])

In [86]:
arr[:3,1:2] 

array([[ 2],
       [12],
       [22]])

In [87]:
arr[:,9]

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [88]:
arr1 = ((np.random.rand(9) * 5).astype(int)).reshape(3,3)
arr2 = ((np.random.rand(9) * 5).astype(int)).reshape(3,3)

In [89]:
arr1


array([[4, 4, 0],
       [4, 0, 1],
       [3, 4, 2]])

In [90]:
arr2

array([[3, 3, 3],
       [3, 0, 2],
       [3, 2, 3]])

In [91]:
arr1+arr2

array([[7, 7, 3],
       [7, 0, 3],
       [6, 6, 5]])

In [92]:
arr1*arr2

array([[12, 12,  0],
       [12,  0,  2],
       [ 9,  8,  6]])

In [93]:
arr1.mean()

2.4444444444444446

In [94]:
arr1.sum()

22