In [1]:
import numpy as np

In [2]:
arr1 = np.array([10,20,30,40,50,60])

In [3]:
arr2 = np.array([1,2,3,4,5,6])

In [4]:
arr1

array([10, 20, 30, 40, 50, 60])

In [5]:
arr2

array([1, 2, 3, 4, 5, 6])

In [6]:
arr1+arr2

array([11, 22, 33, 44, 55, 66])

In [7]:
arr1-arr2

array([ 9, 18, 27, 36, 45, 54])

In [8]:
arr1*arr2

array([ 10,  40,  90, 160, 250, 360])

In [9]:
arr1


array([10, 20, 30, 40, 50, 60])

In [10]:
arr1+10

array([20, 30, 40, 50, 60, 70])

In [11]:
arr2 - 2

array([-1,  0,  1,  2,  3,  4])

In [12]:
arr1

array([10, 20, 30, 40, 50, 60])

In [13]:
arr1/3

array([ 3.33333333,  6.66666667, 10.        , 13.33333333, 16.66666667,
       20.        ])

In [14]:
np.sqrt(arr1)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781,
       7.74596669])