In [1]:
import numpy as np

In [2]:
arr = np.arange(1,10)

In [3]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr[1]

2

In [5]:
arr[2:5]

array([3, 4, 5])

In [6]:
arr[:3]

array([1, 2, 3])

In [7]:
arr[:9]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr[::2]

array([1, 3, 5, 7, 9])

In [9]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr[:3]

array([1, 2, 3])

In [11]:
arr[:3] = 25

In [12]:
arr

array([25, 25, 25,  4,  5,  6,  7,  8,  9])

In [22]:
arr = np.arange(1,10)

In [23]:
arr2 = np.arange(1,5)

In [24]:
arr2

array([1, 2, 3, 4])

In [25]:
arr2 = arr

In [26]:
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
arr2[0:3] = 100

In [28]:
arr2

array([100, 100, 100,   4,   5,   6,   7,   8,   9])

In [29]:
arr

array([100, 100, 100,   4,   5,   6,   7,   8,   9])

In [30]:
arr = np.arange(1,10)

In [31]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
arr2 = arr.copy()

In [33]:
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
arr2[:3]=100

In [36]:
arr2

array([100, 100, 100,   4,   5,   6,   7,   8,   9])

In [37]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
newArray = np.arange(1,21)

In [42]:
newArray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [43]:
newArray = newArray.reshape(5,4)

In [44]:
newArray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [45]:
newArray[0,0]

1

In [46]:
newArray[:,:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18]])

In [47]:
newArray[:2,:2]

array([[1, 2],
       [5, 6]])

In [48]:
newArray[:2,:4]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [49]:
newArray[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [50]:
arr= np.arange(1,11)

In [51]:
arr > 3 

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [52]:
booleanArray = arr > 3

In [53]:
arr[booleanArray]

array([ 4,  5,  6,  7,  8,  9, 10])

In [54]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])